### ISSUE TITLE
请问这个模型怎么用，有没example呢？

### ISSUE THREAD

**Issue by nlpchen** [JieShenAI/torch#1]
https://huggingface.co/jieshenai/zh_en_translation
@JieShenAI

**Comment by nlpchen** [comment]
https://huggingface.co/jieshenai/zh_en_translation
请问这个模型怎么用，
可以发个demo给我吗？想本地运行。nlp_chen@163.com

**Comment by JieShenAI** [comment]
汉译英 例子
https://github.com/JieShenAI/torch/blob/main/huggingface/example/translation/%E8%8B%B1%E6%B1%89%E4%BA%92%E8%AF%91.ipynb

我们会在今日重新梳理一下这个例子，请关注这个文件的最新版本

**Comment by nlpchen** [comment]
> 

感恩的心

**Comment by JieShenAI** [comment]
Demo 已更新
